repositories:
  - name: longhorn
    url: https://charts.longhorn.io
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: cert-manager
    url: https://charts.jetstack.io
  - name: immich
    url: https://immich-app.github.io/immich-charts
---
releases:
  - name: longhorn
    namespace: longhorn-system
    chart: longhorn/longhorn
    version: 1.7.1

  - name: ingress-nginx
    namespace: nginx-system
    chart: ingress-nginx/ingress-nginx
    version: 4.11.2

  - name: cert-manager
    namespace: cert-manager
    chart: cert-manager/cert-manager
    version: 1.15.3
    values:
      - ./cert-manager.values.yaml

  - name: immich
    namespace: immich-system
    chart: immich/immich
    version: 0.7.2
    values:
      - ./immich.values.yaml
