kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-immich
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "2880"
  fromBackup: ""
  fsType: "ext4"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library
  namespace: immich-system
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn-immich
  resources:
    requests:
      storage: 4G
