name: nix-flake-check
on:
  pull_request:
  push:
  workflow_call:
jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: sliteteam/github-action-git-crypt-unlock@1.2.0
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
      - uses: cachix/install-nix-action@v27
      - run: nix flake check -L
